# fly.toml app configuration file for awesomeindex FastAPI app
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'awesomeindex'
primary_region = 'bos'

[build]

[http_service]
internal_port = 8000
force_https = true
auto_stop_machines = 'stop'
auto_start_machines = true
min_machines_running = 0
processes = ['app']

[mounts]
source = "awesomeindex_data"
destination = "/app/data"

[env]
DATABASE_URL = "sqlite:////app/data/awesomeindex.db"
MEILISEARCH_URL = "http://awesomeindex-search.internal:7700"

[[vm]]
memory = '1gb'
cpu_kind = 'shared'
cpus = 1
cpu_kind = 'shared'
cpus = 1
